# COCO80 dataset classes

classes_80 = {
    0: u'__background__',
    1: u'person',
    2: u'bicycle',
    3: u'car',
    4: u'motorcycle',
    5: u'airplane',
    6: u'bus',
    7: u'train',
    8: u'truck',
    9: u'boat',
    10: u'traffic light',
    11: u'fire hydrant',
    12: u'stop sign',
    13: u'parking meter',
    14: u'bench',
    15: u'bird',
    16: u'cat',
    17: u'dog',
    18: u'horse',
    19: u'sheep',
    20: u'cow',
    21: u'elephant',
    22: u'bear',
    23: u'zebra',
    24: u'giraffe',
    25: u'backpack',
    26: u'umbrella',
    27: u'handbag',
    28: u'tie',
    29: u'suitcase',
    30: u'frisbee',
    31: u'skis',
    32: u'snowboard',
    33: u'sports ball',
    34: u'kite',
    35: u'baseball bat',
    36: u'baseball glove',
    37: u'skateboard',
    38: u'surfboard',
    39: u'tennis racket',
    40: u'bottle',
    41: u'wine glass',
    42: u'cup',
    43: u'fork',
    44: u'knife',
    45: u'spoon',
    46: u'bowl',
    47: u'banana',
    48: u'apple',
    49: u'sandwich',
    50: u'orange',
    51: u'broccoli',
    52: u'carrot',
    53: u'hot dog',
    54: u'pizza',
    55: u'donut',
    56: u'cake',
    57: u'chair',
    58: u'couch',
    59: u'potted plant',
    60: u'bed',
    61: u'dining table',
    62: u'toilet',
    63: u'tv',
    64: u'laptop',
    65: u'mouse',
    66: u'remote',
    67: u'keyboard',
    68: u'cell phone',
    69: u'microwave',
    70: u'oven',
    71: u'toaster',
    72: u'sink',
    73: u'refrigerator',
    74: u'book',
    75: u'clock',
    76: u'vase',
    77: u'scissors',
    78: u'teddy bear',
    79: u'hair drier',
    80: u'toothbrush'}

classes_90 = {0: 'N/A',
              1: 'person',
              2: 'bicycle',
              3: 'car',
              4: 'motorcycle',
              5: 'airplane',
              6: 'bus',
              7: 'train',
              8: 'truck',
              9: 'boat',
              10: 'traffic light',
              11: 'fire hydrant',
              12: 'N/A',
              13: 'stop sign',
              14: 'parking meter',
              15: 'bench',
              16: 'bird',
              17: 'cat',
              18: 'dog',
              19: 'horse',
              20: 'sheep',
              21: 'cow',
              22: 'elephant',
              23: 'bear',
              24: 'zebra',
              25: 'giraffe',
              26: 'N/A',
              27: 'backpack',
              28: 'umbrella',
              29: 'N/A',
              30: 'N/A',
              31: 'handbag',
              32: 'tie',
              33: 'suitcase',
              34: 'frisbee',
              35: 'skis',
              36: 'snowboard',
              37: 'sports ball',
              38: 'kite',
              39: 'baseball bat',
              40: 'baseball glove',
              41: 'skateboard',
              42: 'surfboard',
              43: 'tennis racket',
              44: 'bottle',
              45: 'N/A',
              46: 'wine glass',
              47: 'cup',
              48: 'fork',
              49: 'knife',
              50: 'spoon',
              51: 'bowl',
              52: 'banana',
              53: 'apple',
              54: 'sandwich',
              55: 'orange',
              56: 'broccoli',
              57: 'carrot',
              58: 'hot dog',
              59: 'pizza',
              60: 'donut',
              61: 'cake',
              62: 'chair',
              63: 'couch',
              64: 'potted plant',
              65: 'bed',
              66: 'N/A',
              67: 'dining table',
              68: 'N/A',
              69: 'N/A',
              70: 'toilet',
              71: 'N/A',
              72: 'tv',
              73: 'laptop',
              74: 'mouse',
              75: 'remote',
              76: 'keyboard',
              77: 'cell phone',
              78: 'microwave',
              79: 'oven',
              80: 'toaster',
              81: 'sink',
              82: 'refrigerator',
              83: 'N/A',
              84: 'book',
              85: 'clock',
              86: 'vase',
              87: 'scissors',
              88: 'teddy bear',
              89: 'hair drier',
              90: 'toothbrush'}
